<a href="https://colab.research.google.com/github/earo12/Archivos_Python_NLTK/blob/master/Tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Alumno: Eduardo Adriel Romero Obispo

# Tarea 2. Seminario de Matemáticas Aplicadas I

### Ejercicio 1
Importa la librería de numpy, utiliza el método linspace para crear un arreglo numérico "a" de la forma: [0,1,2,...,100], luego crea un arreglo "b" de la forma [100,99,98,...,0]. Suma ambos arreglos en una nueva variable "c" y divide "c" entre 100. Muestra el arreglo resultante y el resultado del método c.sum().

In [ ]:
import numpy as np # importamos numpy as np como usualmente

In [ ]:
a = np.array(range(0,101)) # definimos dos arreglos a y b, a sale con un range de 0 a 101, b sale con un arreglo de 100 a -1 en saltos de -1
b = np.array(range(100,-1,-1)) 
c = (a + b)/100 # definimos a c como (a+b)/100 y aplicamos el metodo .sum con un fstring a c para colocarlo como respuesta de este problema
print(f'Valor final = {c.sum()}')

Valor final = 101.0


### Ejercicio 2
Crea un arreglo matricial con el código: M = np.arange(1,145).reshape(12,12) muestra el resultado y luego extrae el último renglón como una nueva variable "m". Calcula la suma de todos los los valores de "M" y "m" con el método .sum y por medio de un ciclo sin ayuda de métodos.

In [ ]:
M = np.arange(1,145).reshape(12,12)   # esto nos lo pide el problema
print(M)

[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132]
 [133 134 135 136 137 138 139 140 141 142 143 144]]


In [ ]:
m = M [-1:,:] # una forma sería usar el contador de 0 hasta el último número que sería 13, pero es mucho más sencillo si lo hacemos de atrás con -1 y como queremos todas las columnas se ponen dos puntos después de la coma
m # y lo imprimimos

array([[133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144]])

In [ ]:
print(f'La suma de la matriz M es  {M.sum()}')    #imprimimos fácilmente los resultados con .sum
print(f'La suma del último renglón m es {m.sum()}')

La suma de la matriz M es  10440
La suma del último renglón m es 1662


In [ ]:

suma = 0      #necesitamos un doble contador que vaya con cada elemento de la matriz y que al final sume cada componente
elementos = 0
for fila in M:        # con cosas que interviene en matrices usamos un doble for 
  for elemento in fila:
    suma = suma + elemento  # al final sumamos el elemento a la suma, como la suma empieza en cero, el primer elemento no se sumará a nada, pero el segundo se sumará al primero y así sucesivamente
    elementos = elementos + 1 # igual incrementamos el valor de los elementos
 
print(f'Para la matriz M la suma es {suma}')


suma2 = 0
elementos2 = 0
for variable in m:
  for elemento2 in variable:
    suma2 = suma2 + elemento2
    elementos2 = elementos2 + 1

print(f'Para la matriz m la suma es {suma2}') # y vemos que son de hecho las mismas valores que encontramos una celda arriba

Para la matriz M la suma es 10440
Para la matriz m la suma es 1662


### Ejercicio 3
Importa la librería de pandas como pd y utiliza el comando pd.read_csv('calis') para importar un dataframe con las calificaciones bimestrales de un alumno por materia desde el archivo csv que se adjuntó en la tarea (considera que el archivo debe estar en la misma carpeta de enrutamiento que tu trabajo). Reetiqueta los ínidices de fila con los índices [bim_1,bim_2,bim_3,bim_4], añade una columna con el encabezado prom_bim sonde se calcule el promedio bimestral por materia. Muestra el dataframe resultante y calcula el promedio anual del alumno para la materia de Inglés.

In [ ]:
import pandas as pd
# IMPORTANTE, ESTOY TRABAJANDO EN COLAB QUIZAS LAS SIGUIENTES LINEAS RESULTEN EXTRAÑAS PERO SON PARA IMPORTAR DESDE MI COMPUTADORA A COLAB
from google.colab import files
uploaded = files.upload()
import io

Saving calis to calis


In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['calis'])) # en realidad todo eso fue únicamente para definir mi data frame como df 

In [ ]:
df.index = ['bim_1','bim_2','bim_3','bim_4'] # simplemente usamos el método index para evitar que nos genere NaN como valores en las asignaturas
df

Esp  Mat  Ing  Hist  Geo  Fis  Art
bim_1   10    7   10     6   10    8    9
bim_2    7    6    8     6    8   10   10
bim_3   10    8   10     9    9    8    6
bim_4    9    6    9     6    5    6    6

In [ ]:
# en este punto no entendí si promedio bimestral por materia era sacar el promedio de cada fila, para tener 4 promedios o si era sacar el promedio de cada materia, pero no tendría mucho caso, ya que la longitud de la nueva columna será mayor a la de los 4 bimestres y marcará error si hacemos esto 
#prom_esp = df['Esp'].mean()
#prom_mat = df['Mat'].mean()
#prom_ing = df['Ing'].mean()
#prom_geo = df['Geo'].mean()
#prom_fis = df['Fis'].mean()
#prom_art = df['Art'].mean()
#df['prom_bim'] = ['prom_esp','prom_mat','prom_ing','prom_geo','prom_fis','prom_art'] # de cualquier manera las coloco, la idea según era calcular el promedio de cada materia al final, pero como tal no es correcto
promedios = df.mean(axis = 1) # en su caso mejor coloco el promedio de todas las materias en un bimestre, me saldrán 4 valores, cumplen el requisito de que sean de la misma longitud que el índice
df['prom_bim'] = promedios    # creamos la columna
df      # y mostramos el dataframe

Esp  Mat  Ing  Hist  Geo  Fis  Art  prom_bim
bim_1   10    7   10     6   10    8    9  8.571429
bim_2    7    6    8     6    8   10   10  7.857143
bim_3   10    8   10     9    9    8    6  8.571429
bim_4    9    6    9     6    5    6    6  6.714286

In [ ]:
# por otra parte, en inglés se sigue que en los bimestres se tiene la siguiente lista
calificaciones_ingles = [10,8,10,9] 
promedio_ingles = sum(calificaciones_ingles)/len(calificaciones_ingles) # lo que hago es almacenar las calificaciones en una lista, y simplemente sacar el promedio con la suma entre el número de elementos
print(f'El promedio anual del alumno en inglés será: {promedio_ingles}') #con promedio de 9.25

El promedio anual del alumno en inglés será: 9.25


### Ejercicio 4
Compile un patrón de búsqueda que encuentre todas las palabras que sean seguidas por puntos suspensivos. Utilice el método search para encontrar cada una de las posibles coincidencias: `dwell`, `flesh` y `once`. Esto implica que tendrá que correr el método `search` en tres ocasiones, 
modificando cada vez los parámetros de índices inicial y final.
Aclaración: los puntos suspensivos no deben ser parte de la coincidencia; en otras palabras, haga uso de un *lookahead*.

In [ ]:
quote = """
To think that once I culd not see beyond the veil of our reality.
To see those who dwell... behind.
My life now has purpose, for I have learned the frailty of flesh..., and bone.
I was once... a fool.
"""

In [ ]:
import re
pattern = re.compile(r'\w+(?=[{.3}])') # esta es la expresión regular, buscamos un grupo que nos tome los 3 puntitos, luego lo ponemos en una clase y finalmente usamos el método de lookahead para que no nos los tome en cuenta PERO sí sean parte de nuestra consulta, finalmente tomamos todos los elementos disponibles
match0 = pattern.search(quote, 0, 36)   
print(match0) #estas 2 variables son para la parte del primer renglón

match1 = pattern.search(quote, 69, 102)
print(match1) # para el segundo renglón

match2 = pattern.search(quote, 103,181)
print(match2) # para el tercer renglón

match3 = pattern.search(quote,182,203)
print(match3) # para el último renglón




None
<re.Match object; span=(84, 89), match='dwell'>
<re.Match object; span=(160, 165), match='flesh'>
<re.Match object; span=(186, 190), match='once'>


### Ejercicio 5

Sea `output` la salida del comando `ls -l`. Comiple un patŕon de búsqueda que encuentre una coincidencia por archivo `.py`; la coincidencia debe incluir el peso del archivo, la fecha y hora de última modificación, y el nombre del archivo. Para esto, utilice el método `findall` e imprima la lista que éste devuelve.
Nótese que el peso del archivo es la columna que sigue al segundo `root`.

In [ ]:
output = """
total 18676
-rw-rw-r-- 1 root root     507 sep  9 12:43 args
-rw-rw-r-- 1 root root 9383156 jun 30 12:03 docs
-rw-rw-r-- 1 root root     901 ago 12 19:27 cleanse.py
-rw-rw-r-- 1 root root    3222 sep  9 12:32 correct__counts.py
-rw-rw-r-- 1 root root    1935 ago 17 18:27 correct_tracking.py
-rw-rw-r-- 1 root root    2017 sep  1 22:52 correct_track.py
-rw-rw-r-- 1 root root    1172 jul  8 11:24 get_pass.py
-rw-rw-r-- 1 root root     382 may 10 13:06 get_errors.py
-rw-rw-r-- 1 root root   24150 may 10 19:23 get_status.py
-rw-rw-r-- 1 root root    1632 jul 29 11:58 get_unprocessed.py
-rw-rw-r-- 1 root root     601 jun 10 00:33 get_nums.py
-rw-rw-r-- 1 root root     659 ago 17 21:00 insert_docs.py
-rw-rw-r-- 1 root root    1277 jun  7 20:35 monthly_update_historic.py
-rw-rw-r-- 1 root root    1493 sep 10 02:04 monthly_update.py
-rw-rw-r-- 1 root root    2017 jun 28 19:18 out
-rw-rw-r-- 1 root root  596625 jul 10 16:51 query2.log
-rw-rw-r-- 1 root root   38104 may 10 20:04 query2.py
-rw-rw-r-- 1 root root  597313 jul 11 16:38 query3.log
-rw-rw-r-- 1 root root  597257 jul 13 18:19 query.log
-rw-rw-r-- 1 root root     647 sep  1 22:27 query.py
-rw-rw-r-- 1 root root     845 ago 12 19:25 restart_tracking.py
-rw-rw-r-- 1 root root     707 sep 10 02:04 update.py
-rw-rw-r-- 1 root root 7803707 ago 17 19:00 ids.txt
-rw-rw-r-- 1 root root    4096 may  1 18:32 verify_tracking_migration.py
-rw-rw-r-- 1 root root     355 sep 10 02:03 x
"""

In [ ]:
# este problema requiere de una consulta bastante larga, lo más avanzado fue esto:
pattern = re.compile(r'(\d+) (\w+) (?<= )\d+(?= ) ([\d]+:[\d]+) ([\w]+.[p]y$)', re.M) # basicamente buscamos caracteres numericos de ahí el \d+ luego son caracteres alfanumericos y numéricos separados por un espacio por ello el lookbehind y lookahead, luego volvemos a colocar dos clases con valores numéricos entre dos puntos para la hora para finalmente poner el.py como una clase con p  
match_list = pattern.findall(output)
print(match_list)

[('901', 'ago', '19:27', 'cleanse.py'), ('1935', 'ago', '18:27', 'correct_tracking.py'), ('382', 'may', '13:06', 'get_errors.py'), ('24150', 'may', '19:23', 'get_status.py'), ('1632', 'jul', '11:58', 'get_unprocessed.py'), ('601', 'jun', '00:33', 'get_nums.py'), ('659', 'ago', '21:00', 'insert_docs.py'), ('1493', 'sep', '02:04', 'monthly_update.py'), ('38104', 'may', '20:04', 'query2.py'), ('845', 'ago', '19:25', 'restart_tracking.py'), ('707', 'sep', '02:04', 'update.py')]


### Ejercicio 6

En la siguiente celda está definida la variable `index` como cadena de texto; es el índice de la Gaceta Legislativa de la LVIII Legislatura de Querétaro. Compila un patrón de búsqueda y utiliza el método finditer para encontrar una coincidencia por índice; es decir, la primera coincidencia debería ser `Orden del Día......3`, la segunda coincidecia debería ser `Acta de la Sesión Solemne del Pleno de la Quincuagésima Octava Legislatura del Estado de Querétaro, de fecha 6 de julio de 2017. ......4`, y así sucesivamente. Además, crea tu patrón de búsqueda con dos agrupaciones, de tal forma que el primer grupo sea el título del índice y el segundo sea la página. Por ejemplo, en la primera coincidencia, el primer grupo debería ser `Orden del día` y el segundo grupo debería ser `3`.
Imprima sus resultados con un ciclo `for` sobre el iterador que devuelve el método `finditer`; imprima tanto la coincidencia completa como los grupos.

Tips:
- Recuerden la bandera de compilación `re.M`
- El metacaracter para el salto de línea es `\n`
- ¡Importante! Recuerden cómo convertir a un cuantificador en perezoso.




In [ ]:
index = """
Orden del Día ...........................................................................................................................3

Acta de la Sesión Solemne del Pleno de la Quincuagésima Octava Legislatura del Estado
de Querétaro, de fecha 6 de julio de 2017. .................................................................................4

Acta de la Sesión Ordinaria del Pleno de la Quincuagésima Octava Legislatura del Estado
de Querétaro, de fecha 6 de julio de 2017. .................................................................................5

Acta de la Sesión Solemne del Pleno de la Quincuagésima Octava Legislatura del Estado
de Querétaro, de fecha 13 de julio de 2017. ...............................................................................9

Comunicaciones Oficiales ......................................................................................................... 10

Turno de Iniciativas ................................................................................................................. 11

Dictamen de la iniciativa para exhortar al Francisco Domínguez Servién, para que en
ejercicio de las facultades como gobernador del Estado de Querétaro, realice la
declaratoria como Patrimonio Cultural Intangible de la Fiesta de San Miguel Arcángel en
el Poblado de San Miguel, Municipio de Tolimán. Presentado por la Comisión de
Educación, Cultura, Ciencia, Tecnología e Innovación. (Discusión y Votación) (Sentido:
Aprobación) ............................................................................................................................ 13

Dictamen de la iniciativa para exhortar al M.V.Z. Francisco Domínguez Servién, para que
en ejercicio de las facultades como gobernador del Estado de Querétaro, realice la
declaratoria como Patrimonio Cultural Intangible de la Artesanía denominada Muñeca de
Artesanal de Amealco. Presentado por la Comisión de Educación, Cultura, Ciencia,
Tecnología e Innovación. (Discusión y Votación) (Sentido: Aprobación) ...................................... 15

Dictamen de la Iniciativa de Ley que reforma, adiciona y deroga diversas disposiciones
del Código Penal para el Estado de Querétaro en materia de combate la corrupción.
Presentado por la Comisión de Administración y Procuración de Justicia. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 17

Dictamen de la Iniciativa de Ley Orgánica de la Fiscalía General del Estado de Querétaro.
Presentado por la Comisión de Administración y Procuración de Justicia. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 25

Dictamen de las Iniciativas de Ley de Protección de Datos Personales en Posesión de
Sujetos Obligados del Estado de Querétaro. Presentado por la Comisión de Derechos
Humanos y Acceso a la Información Pública. (Discusión y Votación) (Sentido:
Aprobación) ............................................................................................................................ 29

Dictamen de la Iniciativa de Decreto para declarar el año 2018 como Año de la Mujer.
Presentado por la Comisión de Igualdad de Género, Grupos Vulnerables y Discriminados.
(Discusión y Votación) (Sentido: Aprobación) ............................................................................ 55

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Ofelia Teresita Gómez
González. Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 57

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Ma. Guadalupe Pérez
Saavedra. Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 59

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Juana Ávila García.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 61

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Estela Amaro Ramírez.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 63

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Lucia Sánchez Sánchez.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 65

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Delia Rincón Lara.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 67

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Teresa Soto Álvarez.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 69

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. Amelia García Araujo.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 70

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. María Guadalupe Aguilar
Landaverde. Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 72

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. María Dolores Cervantes
Malagón. Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y
Votación) (Sentido: Aprobación) ............................................................................................... 74

Dictamen de la Solicitud de Pensión por Muerte a favor de la C. J. Jesús González Jaime.
Presentado por la Comisión de Trabajo y Previsión Social. (Discusión y Votación)
(Sentido: Aprobación) ............................................................................................................. 76

"""

In [ ]:
prueba = "Orden del Día ...........................................................................................................................3"

In [ ]:
#Les comparto que hice, estaré atento a cualquier retroalimentación que me puedan dar, prefiero aprender de mis errores:
import re 

pattern = re.compile(r'(^.+\w (?=[{.??}]) (\d+))', re.M) # lo que yo busco es crear una expresión regular usando re.M tal que los inicios de la cadena sean los mismos, en este caso tomar cualquier caracter con \w y hacer "perezoso" con el ?  para cada puntito que funciona como indice finalmente considerar valores numericos con \d+
match_list = pattern.findall(prueba) #primero hay que usar el método findall con el indice de prueba
print(match_list)

[]


In [ ]:
match_iter = pattern.finditer(prueba) # después hacer uso del método finditer como se vio en una ayudantía 
print(match_iter)

In [ ]:
for i, match in enumerate(match_iter):
    print(f'match {i}:', match) #y finalmente imprimir los valores cadena por cadena con for pero no logré hacer nada

### Ejercicio 7

Crea una función en python tal que dada una función matemática (evaluada sobre los números reales) cualquiera y un intervalo cualquiera, calcule su integral definida.

In [ ]:
def f(x): # aqui se puede cambiar el valor de la función
  return x**4 + 5*x**3 - 2*x**2 + 3*x -5

In [ ]:
a = float(input('Introduce el valor de a: '))
b  = float(input('Introduce el valor de b: '))
n = int(input('Introduce el valor de las particiones, asegúrate de introducir un número entero: '))
delta = (b-a)/n
def calculadora_integral(a, b, n):
  suma = 0  # iniciamos el contador de suma que incrementara conforme apliquemos la regla de recurrencia de la suma de riemman
  paso = 0
  for i in range(1,n+1):
    suma = suma + f((a+(i-1/2))*delta)
    paso = (b-a)/n*suma   # al final el paso será el resultado correspondiente a la integral
  return paso
calculadora_integral(a,b,n)   #finalmente llamamos a la función para que trabaje

Introduce el valor de a: 0
Introduce el valor de b: 10
Introduce el valor de las particiones, asegúrate de introducir un número entero: 10000


31933.3331058334

### Ejercicio 8 

Crea una función en python tal que dada una función matemática cualquiera (evaluada sobre los números reales) encuentre los ceros de la función en un intervalo si es que existen. Esto significa que se buscan los puntos $x\in[a,b]\subset \mathbb{R}$ tales que $f(x) = 0$ .

In [ ]:
def f(x):
  return x**2-3 #esta funcion puede ser cambiada

In [ ]:
# en si hay distintos métodos, este es el método de la secante buscamos que un punto x1 cumpla la condición x1=x0-f(x0)/((f(x0)-f(x1))/(x0-x1)) 
x0 = float(input('Introduce el primer valor donde creas que está la raíz de la función: '))
x1 = float(input('Introduce el segundo valor donde creas que está la raíz de la función: '))
n = int(input('Ahora introduce el número de iteraciones que quieras usar, por favor introduce un número entero: '))
def ceros(f,x0,x1,n):
  for valor in range(1, n): # empezamos las iteraciones con los valores ingresadas anteriormente
    f0 = f(x0)
    f1 = f(x1)
    xi = x0 - (f0/((f0-f1)/(x0-x1)))    # esta es la relación que puse arriba
    x0 = x1
    x1 = xi  # se cumplira hasta que se tengan las siguientes condiciones
    print(f'La raíz se encuentra en x = {xi} con {n} iteraciones') # finalmente se dará un valor correspondiente de cada raíz
ceros(f,x0,x1,n) #imprime el valor final de los ceros que para este caso se podría decir son 2 el primero 1.32 y el segundo 1.73

Introduce el primer valor donde creas que está la raíz de la función: 1
Introduce el segundo valor donde creas que está la raíz de la función: 10
Ahora introduce el número de iteraciones que quieras usar, por favor introduce un número entero: 10
La raíz se encuentra en x = 1.1818181818181819 con 10 iteraciones
La raíz se encuentra en x = 1.3252032520325194 con 10 iteraciones
La raíz se encuentra en x = 1.8213443396226419 con 10 iteraciones
La raíz se encuentra en x = 1.7205051836165723 con 10 iteraciones
La raíz se encuentra en x = 1.7317597309616692 con 10 iteraciones
La raíz se encuentra en x = 1.7320517810344518 con 10 iteraciones
La raíz se encuentra en x = 1.7320508074870735 con 10 iteraciones
La raíz se encuentra en x = 1.7320508075688772 con 10 iteraciones
La raíz se encuentra en x = 1.7320508075688774 con 10 iteraciones


## Ejercicio 9

Crea una función en python tal que dada una matriz cuadrada (con entrada en los números complejos) de cualquier tamaño, calcule sus valores propios y sus vectores propios.


In [ ]:
def matriz():
  return np.array([[3+10j,4+5j],[7+2j,-3+8j]]) # aquí se puede cambiar los elementos de la matriz, no nos mencionan si es el usuario quien debe declararla al ejecutar el programa
matriz() # aqui vemos la matriz que creamos

array([[ 3.+10.j,  4. +5.j],
       [ 7. +2.j, -3. +8.j]])

In [ ]:
def valores_vectores(matriz): # en realidad solo depende del valor que tendrá la matriz anterior
  eingenvalues,eigenvectors=np.linalg.eig(matriz) # hay una atributo de numpy que nos permite calcular los valores y vectores propios llamado linalg con ello podemos hacer esta parte del proceso
  return eingenvalues, eigenvectors

print(f'Valores propios de la matriz = {eingenvalues}') #imprimimos los valores y vectores
print(f'Vectores propios de la matriz = {eigenvectors}')

Valores propios de la matriz = [1.+2.j 1.+0.j]
Vectores propios de la matriz = [[ 0.70710678+0.00000000e+00j  0.70710678+0.00000000e+00j]
 [ 0.70710678+0.00000000e+00j -0.70710678-1.38777878e-17j]]


### Ejercicio 10
n
Crea una función en python tal que dado cualquier número natural se regrese la descomposición en factores de primos de dicho número. Esto significa que se regresaría una lista de duplas; cada entrada de la lista es una tupla donde la primera entrada es el número primo y la segunda entrada es el exponente. Ejemplo:

Para el número $ 3720937500 $ tiene una descompoción de la siguiente forma:

$ 3720937500 = 2^2 3^5 5^7 7^2$

por lo que lo que se buscaría es que la salida sea:

[(2,2),(3,5),(5,7),(7,2)]

In [ ]:
valor = int(input('Introduce el número que quieras transformar: '))
def numeros_primos(valor):
    i = 2 # iterador sobre el número
    primos = [] # Lista vacía para depositar los factores y exponentes
    while i* i <= valor: 
        if valor % i == 0:  # buscamos que el modulo del numero sea cero, si eso se cumple se tendra el iterador sobre el exponente que se desea almacenar como lista
            expo = 0
            while valor % i == 0: 
                expo = expo +1 #expo += 1
                valor = valor/i #n /= i   # en este ciclo se busca iterar sobre el numero que el usuario introduce e irlo dividiendo hasta que el módulo de esta división con el iterador sea cero
                primos.append([i,expo]) # para juntarlos en la lista primos
        i = i+1 #i += 1

    if valor > 1: # siempre que se tenga un número mayor a 1 introducido por el usuario, se dará su primer valor 
        primos.append([valor,1])

    return primos
print(f'La descomposición será: {descom_primos(valor)}') #este algoritmo funciona para numeros pequeños por ejemplo el 15 

Introduce el número que quieras transformar: 15
La descomposición será: [[3, 1], [5.0, 1]]


In [ ]:
valor = 3720937500
numeros_primos(valor)
print(f'La descomposición será: {descom_primos(valor)}') # sin embargo con el ejemplo que ponen se repite cada cuantas veces aparece la potencia y no entrega el valor máximo del exponente


La descomposición será: [[2, 1], [2, 2], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5], [5, 6], [5, 7], [7, 1], [7, 2]]


### Ejercicio 11 

El algoritmo de la distancia de Levenshtein se muestra en la siguiente celda.

Demuestre que la distancia de Levenshtein es en efecto una métrica. Es decir, demuestre (de manera formal y rigurosa) que:

$\mathcal{L} = \{a,b,c,d,...,z,A,B,C,...,Z,1,2,3,4,..,9,0, _ \> \}$


$Wordspace = \mathcal{L}\times \mathcal{L} \times... $


$ d(x,y)=0$ $sii$ $x=y$ $\forall x,y \in Wordspace$

$ d(x,y)=d(y,x)$  $\forall x,y \in Wordspace$

$ d(x,z)\leq d(x,y)+d(y,z)$  $\forall x,y,z \in Wordspace$


Con esta demostración se ha justificado que $Wordspace$ es un espacio métrico

(Nota: Aquí el último elemento de $\mathcal{L}$ trata de denotar el espacio en blanco.)


# Punto Extra

¿Cuál es la cardinalidad de $Wordspace$? Justifique su respuesta












Para mostrar que $\mathcal{L}$ es una métrica tenemos que ver que se cumplan los 3 axiomas de una métrica con alguno de sus elementos, en efecto:

$i)$ Sea  $x = a$ y $y = a $ con $a\in Wordspace$ tenemos que:
$$
d(x,y) = d(a,a) = d(0) = 0$$ $$\therefore d(x,y) = 0 \forall a \in Wordspace $$ con $x = y$ , pues $0\in Wordspace$

$ii)$ Sean $x = a$ y $y = b$ con $a,b\in Wordspace$, entonces tenemos que:
$$
d(x,y) = d(a,b) = |a-b| = |(-1)(b-a)|
$$
$$
= |-1||b-a| = |b-a| = d(b,a) = d(y,x)
$$

$$
\therefore d(a,b) = d(b,a) \forall a,b\in Wordspace
$$



$iii)$  Sean $x = a$, $y = b$ y $z = c$ con $a,b,c\in Wordspcae$ entonces tenemos que:
$$
d(x,y) = d(a,b) = |a-b|
$$

$$
= |a-b+(c-c)| = |(a-c)+(b-c)|
$$

$$
\leq |a-c|+|b-c|
$$ (esto es debido a uno de los axiomas de espacios métricos)

$$ 
=d(a,c)+d(b,c) = d(x,z)+d(z,y)
$$

$$
\therefore d(a,b) \leq d(a,c) + d(c,b) \forall a,b,c \in Wordspace
$$

Y por lo tanto $Wordspace$ es un espacio métrico.



La cardinalidad de Wordspace es finita, pues se tiene que el conjunto L es finito en cuanto a dimensión, al realizar el producto cartesiano se tendrá un producto de elementos finitos cada uno con una cardinalidad de 65 elementos (considerando a la ñ como uno de sus elementos, se tendrán 27 minúsculas, 27 mayúsculas, 10 dígitos y un espacio blanco), al ser multiplicado n veces tendremos una cardinalidad de $65\cdot 65\cdot 65\cdots 65$ n veces, de tal forma que la cardinalidad en este caso será $65^n$ con n el número de veces que fue multiplicada la métrica $\mathcal{L}$.

In [ ]:
import numpy as np

def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
                print(matrix[x-1, y] + 1,matrix[x-1, y-1],matrix[x, y-1] + 1)
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
                print(matrix[x-1,y] + 1,matrix[x-1,y-1] + 1,matrix[x,y-1] + 1)
            print(matrix)
            print('---------')
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

In [ ]:
levenshtein('Roberto','Carlos')

2.0 1.0 2.0
[[0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0.]]
---------
3.0 2.0 2.0
[[0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 2. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0.]]
---------
4.0 3.0 3.0
[[0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 2. 3. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0.]]
---------
5.0 4.0 4.0
[[0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 2. 3. 4. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0.]]
---------
6.0 5.0 5.0
[[0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 2. 3. 4. 5. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 

6.0